### ISSUE TITLE
Weird lua error on awesome startup

### ISSUE THREAD

**Issue by cyril-marpaud** [HikariKnight/material-awesome#15]
Hi @HikariKnight,
First of all, sorry if this ain't the place for questions... and thx for your work, it looks awesome & I can't wait to have a up & running setup that uses it.
I've spent most of the day trying to install your theme but I can't seem to make my way around what I think is a lua error when awesomewm starts.

I've also tried to install themes from https://github.com/manilarome/the-glorious-dotfiles but a similar error shows up & awesome stays ugly :(

![image](https://user-images.githubusercontent.com/9333398/109432201-694f5300-7a0a-11eb-976a-8edee6094c17.png)

I've downloaded a debian-testing img & installed it in virtualbox, built awesome from source using the instructions at https://github.com/awesomeWM/awesome/tree/master#debian-based & then installed the dependencies.

Have I missed something along the way, like a dependency or anything that could cause such an error ?
Is there any procedure that I could follow coming from a clean no-DE environment ?

Thx in advance.

PS : the actual error that shows up says there's a probem with this line : https://github.com/HikariKnight/material-awesome/blob/a57bd52ec12991b07618cca6bbea8b20595f19fa/theme/default-theme.lua#L49
which is the first line where gtk_variable() is called. That might help you understand what could be wrong...

**Comment by HikariKnight** [comment]
you could try change any instance of gtk_variable().whatever into an actual color hex as the gtk_variable() function fetches settings from the gtk/gnome system (i see it used to fetch gtk color settings in the code)

so maybe because of that, it will not work when coming from a no-DE environment. that would be my guess

**Comment by cyril-marpaud** [comment]
I've tried reinstalling debian with gnome & then only, recompile awesome and reinstall other dependencies (instead of coming from a no-DE env).
I don't have the weird lua error anymore, I can see the theme being setup although nothing seems "clickable" (so clearly not usable but there's progress, thx for the insight !).
I used https://github.com/manilarome/the-glorious-dotfiles but i'll try again using your repo today or tomorrow and keep you posted.

**Comment by HikariKnight** [comment]
please do

**Comment by cyril-marpaud** [comment]
Progress, but still totally unusable.
I'll try it again this weekend on a real laptop rather than in virtualBox, i see weird resolution & display issues that might disappear on a real setup.

![image](https://user-images.githubusercontent.com/9333398/109870208-196ec700-7c6a-11eb-9b06-73c0cf83789b.png)

**Comment by HikariKnight** [comment]
Pretty sure that is caused by virtualbox (primarily the "resize vm to window" option and the vbox display driver), try restarting awesome and see if the resolution is re-set as awesome only checks resolution for panels and such ONCE when starting up, restarting awesome should re-run that check.

right click the wallpaper --> awesome --> restart
or press CTRL+SUPER+R

**Comment by HikariKnight** [comment]
hey @Fointard is this still an issue?

**Comment by cyril-marpaud** [comment]
Hi, sorry for the tardiness, I was supposed to receive my new laptop like 2 weeks ago & make the test on real hardware but it still hasn't been sent :( I didn't forget about you though, i will make the test & keep you posted.

**Comment by HikariKnight** [comment]
ok 👍

**Comment by BarrelKnight723** [comment]
![IMG_0769](https://user-images.githubusercontent.com/61663667/115127024-736ce700-9fa1-11eb-895e-3ff28f53805b.jpg)
These are the errors that I have gotten and I also have the display settings error. It seems that there are some missing files so I will try to clone the config file again.

**Comment by BarrelKnight723** [comment]
I just tried to clone it again and the error was still there. I will try another pork and will let you know which one it is if it works.

**Comment by HikariKnight** [comment]
@CSForever07 step 1
![image](https://user-images.githubusercontent.com/2557889/115128298-11ca6e00-9fdd-11eb-9108-7e2ea72acca3.png)

the current "stable" awesomewm in most distro repositories does not have the ruled library as it was added to the master branch after the stable release of awesome 4.3

**Comment by BarrelKnight723** [comment]
Oh ok, I will try that and will keep you posted.

**Comment by HikariKnight** [comment]
👍

**Comment by cyril-marpaud** [comment]
Hi @HikariKnight,
New laptop reception was further delayed due to the ongoing shortage, I had to quickly install another distro to start working asap as I couldn't afford to spend more time on configuration :(
I might come back to your awesome work some day but not in the near future, pls close this issue & sorry for the inconvenience...
(thx anyway for the work & support !)
