### ISSUE TITLE
Any way to call the exit screen by a keybinding?

### ISSUE THREAD

**Issue by thepenguinthatwants** [HikariKnight/material-awesome#17]
Hi,
Your exit_screen looks super nice.
I am a keyboard based person so I was wondering if there is any easy way to implement calling exit_screen by keybinding.
As the exit-screen is module I am curious if its possible and easy to just include it in my own awesome setup.

I am quite new with lua and awesome so being getting load of errors without success.
I added this.

`require('module.exit-screen')`

I guess it could somehow map the keybinding to call
	
'module::exit_screen:show',

**Comment by HikariKnight** [comment]
i am quite new to lua myself as this is a fork from the original project with some new stuff from another project added into it, but i will have a look and see if i can get it to load.
for some reason github didnt notify me about this issue so i missed it, sorry for the extremely late reply @thepenguinthatwants

**Comment by HikariKnight** [comment]
@thepenguinthatwants hey, this should be as simple as adding

`awesome.emit_signal('module::exit_screen:show')`

into the hotkeys function block like this example
```
awful.key(
		{'Control', altkey},
		'Delete',
		function()
			awesome.emit_signal('module::exit_screen:show')
		end,
		{description = 'Show end session screen', group = 'awesome'}
	),
```

PS: actually gone ahead and made this part of the default config now

**Comment by HikariKnight** [comment]
@thepenguinthatwants implemented in the newest commits now :)
