### ISSUE TITLE
can not find ruled.init

### ISSUE THREAD

**Issue by githubb11** [HikariKnight/material-awesome#19]
![44](https://user-images.githubusercontent.com/89767783/143730368-efad774f-929b-4fbc-9ffc-1e90652bfbda.png)

**Comment by HikariKnight** [comment]
it is caused by not having the newest awesomewm as ruled got introduced in a subversion after 4.3 which most distros do not have included in their repos
![image](https://user-images.githubusercontent.com/2557889/144937525-f41e40ea-3d9a-4146-ac37-912716f1d59e.png)
