### ISSUE TITLE
how to change window gap size and selected icon border color?

### ISSUE THREAD

**Issue by InvisibleRasta** [HikariKnight/material-awesome#2]
hello, i ahve been going trought the config for over 2 hours.. i cant figure out how to change the two things i described in the title. maybe you can help me? thank you

**Comment by XeoSpheric** [comment]
theme/PapyElGringo-theme/init.lua then find theme.accent = mat_colors. This is what worked for me at least. The gap I am looking for as well. I forked the project and this is what I have for the changes theme wise.

![image](https://user-images.githubusercontent.com/8729260/85424756-8bb4d680-b535-11ea-815c-0236d34e6aed.png)

**Comment by linuxdotexe** [comment]
window gap size is in `awesome/configuration/tags/init.lua` under `awful.screen.connect_for_each_screen` function. edit the value "gap".

**Comment by HikariKnight** [comment]
seems like this has been answered now, my bad for not noticing this earlier
