### ISSUE TITLE
Edit drawer menu color

### ISSUE THREAD

**Issue by IceDBorn** [HikariKnight/material-awesome#20]
![image](https://user-images.githubusercontent.com/51162078/149655481-e39e9bc0-38f4-491b-8b47-dbc362fbdafd.png)
I'm trying to edit the drawer menu color (blue) and I can't find the line I have to edit.

**Comment by IceDBorn** [comment]
@HikariKnight

**Comment by HikariKnight** [comment]
@IceDBorn line 29 in https://github.com/HikariKnight/material-awesome/blob/master/layout/left-panel/action-bar.lua :)

**Comment by IceDBorn** [comment]
You are right, thank you!
