### ISSUE TITLE
Weather widget is not working

### ISSUE THREAD

**Issue by IceDBorn** [HikariKnight/material-awesome#22]
![image](https://user-images.githubusercontent.com/51162078/150118718-41a0b1f8-7665-48e5-a412-606ac7e763da.png)
@HikariKnight

**Comment by HikariKnight** [comment]
@IceDBorn have you configured it in configuration/config.lua ?
as it is not a widget i personally use but i kept it from the original theme as someone might find it useful.

It requires you to get a free API key from https://openweathermap.org/api when i look at the source for the widget and the config

**Comment by IceDBorn** [comment]
Thnx for the info

**Comment by IceDBorn** [comment]
@HikariKnight How do I remove it?

**Comment by HikariKnight** [comment]
unsure as i just keep it there to fill the empty void. but i would assume you remove the widgets include/require where it is referenced 🤔
think that is all that should be required for widgets.

**Comment by HikariKnight** [comment]
yes just checked it @IceDBorn you just comment out the weather widget require in layout/right-panel/init.lua

**Comment by IceDBorn** [comment]
Thanks a lot! You're the best! Btw, what plugins are you using for sound on the tray and input layout?

**Comment by IceDBorn** [comment]
@HikariKnight

**Comment by HikariKnight** [comment]
@IceDBorn 
ibus for input

i do not have sound on the tray as i always use pavucontrol and pacmd for more advanced things and adjust the volume using the left panel or the audio slider on my headset.
