### ISSUE TITLE
Config broken on latest arch awesome git

### ISSUE THREAD

**Issue by IceDBorn** [HikariKnight/material-awesome#25]
`Oops, an error happened! /home/icedborn/.config/awesome/layout/init.lua:28: attemp to index a nil value (field top_panel)`

It happens with other values if you disable the one on 28.

**Comment by IceDBorn** [comment]
@HikariKnight

**Comment by HikariKnight** [comment]
hey @IceDBorn checkout the lua5.4 branch, it has a fix for this
sorry for not messaging here, its been a busy time for me irl
