### ISSUE TITLE
How to change the wallpaper in the latest Awesome 4.3

### ISSUE THREAD

**Issue by GsnMithra** [HikariKnight/material-awesome#5]
Hey Hikari,
I think you remember me from the CTT channel. I have some problems changing the wallpaper in the new updated version of the AwesomeWM. All the other forums are based on the older version of Awesome. 

I use all the default script files that came out of the box. 

Thanks Hikari!

**Comment by HikariKnight** [comment]
i didnt see this until now, my bad!
i believe i either just used nitrogen or just located the path in the lua files and changed that
