### ISSUE TITLE
how to add/remove workspaces

### ISSUE THREAD

**Issue by jgx0** [HikariKnight/material-awesome#9]
How do i add or remove workspaces?

**Comment by linuxdotexe** [comment]
Navigate to `/awesome/configuration/tags/init.lua` and add as new tags under `local tags` in the format used for the others.

**Comment by HikariKnight** [comment]
@orangemn6 seems like @sainivasmangu got it it before me, i have been busy irl so i did not notice the issue tracker had activity :sweat_smile:
